[package]
name = "blockfrost"
version = "0.2.0"
edition = "2021"
description = "A Rust SDK for Blockfrost.io API"
license = "Apache-2.0"
repository = "https://github.com/blockfrost/blockfrost-rust"
homepage = "https://blockfrost.io"

[dependencies]
hex = "0.4"
futures = "0.3.17"
reqwest = { version = "0.11.4", features = ["multipart"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version ="1.0.68", features = ["arbitrary_precision"] }
paste = "1.0"
toml = "0.5.8"

# Used in examples/
[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
